build:
	gcc src/main.c src/operations/addition.c src/operations/subtraction.c src/operations/multiplication.c src/operations/division.c src/operandstack.c src/operatorstack.c src/check_exp.c src/evaluate.c -o main
run:
	./main
clean:
	rm main
